### ISSUE TITLE
Requests errors

### ISSUE THREAD

**Issue by psasin36156** [BlathanAevon/berachain_faucet_claimer#1]
Failed request, reason: <bound method ClientResponse.text of <ClientResponse(https://bartio-faucet.berachain-devnet.com/api/claim?address=0xCf961A6b0fBF7d4a102f5d0040CE9892095252DE) [402 Payment Required]>
<CIMultiDictProxy('Content-Type': 'application/json', 'Vary': 'Origin', 'Date': 'Tue, 25 Jun 2024 18:16:29 GMT', 'Content-Length': '2', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')>

**Comment by BlathanAevon** [comment]
The faucet requires you to have at least 0.001 ETH in Ethereum mainnet to work.

**Comment by psasin36156** [comment]
Thanks ser.
